name:                hw1
version:             0.1.0.0
github:              "NelosG/fp-tests"
license:             GPL-3
author:              "Leonid Vasilev && Gleb Pushkarev"
maintainer:          "vasiklenka@gmail.com or gleb.pushkarev@gmail.com"
copyright:           "2021 Leonid Vasilev && Gleb Pushkarev"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/NelosG/fp-tests/blob/master/hw1/README.md>
homepage:       https://github.com/NelosG/fp-tests/blob/master/hw1/README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hw1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1

tests:
  t1:
    main:                Spec.hs
    source-dirs:         test/T1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1
    - tasty-hspec
    - tasty-hedgehog
    - tasty
    - hspec
    - hedgehog
    - containers
  t2:
    main:                Spec.hs
    source-dirs:         test/T2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1
    - tasty-hspec
    - tasty-hedgehog
    - tasty
    - hspec
    - hedgehog
    - containers
  t3-4:
    main:                Spec.hs
    source-dirs:         test/T3T4
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1
    - tasty-hspec
    - tasty-hedgehog
    - tasty
    - hspec
    - hedgehog
    - containers
  t5:
    main:                Spec.hs
    source-dirs:         test/T5
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1
    - tasty-hspec
    - tasty-hedgehog
    - tasty
    - hspec
    - hedgehog
    - containers
  t6:
    main:                Spec.hs
    source-dirs:         test/T6
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1
    - tasty-hspec
    - tasty-hedgehog
    - tasty
    - hspec
    - hedgehog
    - containers
  t7:
    main:                Spec.hs
    source-dirs:         test/T7
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1
    - tasty-hspec
    - tasty-hedgehog
    - tasty
    - hspec
    - hedgehog
    - containers